version: '2'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  memcached:
    image: memcached:latest
    restart: always
  elasticsearch:
    image: elasticsearch:5
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: always
    build: ./dockerfiles/php-fpm
    extra_hosts:
      - "docker-local.dev:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
  gearman:
    image: kendu/gearman:latest
    restart: always
  worker:
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/wp-gears-worker/php.ini:/usr/local/etc/php/php.ini"
      - "./config/wp-gears-worker/supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./config/wp-gears-worker/conf.d:/etc/supervisor/conf.d"
    restart: always
    build: ./dockerfiles/wp-gears-worker
